server:
  port: 8081

spring:
  application:
    name: employees-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/employees
    username: employees
    password: employees
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:db/db-changelog.yaml
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      group-id: employees-backend
      properties:
        spring:
          json:
            trusted:
              packages: employees

logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE
