server:
  port: 8080

spring:
  application:
    name: employees-frontend
  cloud:
    stream:
      function:
        bindings:
          employeeCreated-in-0: employees-backend-response
      bindings:
        employees-backend-request:
          content-type: application/*+avro

logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE
    org:
      springframework:
        core:
          retry: debug

employees:
  backend-url: http://localhost:8081