server:
  port: 8081

spring:
  application:
    name: employees-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/employees
    username: employees
    password: employees
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:db/db-changelog.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/EmployeesRealm
logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE
